# Generated by Django 2.0.6 on 2018-07-21 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishersalesreport',
            name='publisher',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='books.Publisher'),
        ),
        migrations.AddField(
            model_name='lowinvreport',
            name='low_inventory_books',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
    ]
