# Generated by Django 2.0.6 on 2018-06-16 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('books', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eodreport',
            name='orders',
            field=models.ManyToManyField(to='cart.Order'),
        ),
        migrations.AddField(
            model_name='booksalesreport',
            name='book',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='books.Book'),
        ),
    ]
