# Generated by Django 2.0.6 on 2018-07-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20180720_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksalesreport',
            name='book',
            field=models.ManyToManyField(blank=True, to='cart.CartItem'),
        ),
        migrations.AlterField(
            model_name='publishersalesreport',
            name='publisher',
            field=models.ManyToManyField(blank=True, to='cart.CartItem'),
        ),
    ]
