# Generated by Django 2.0.6 on 2018-07-16 00:21

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='item_picture',
            field=models.ImageField(blank=True, default='static/images/img.png', null=True, upload_to=books.models.upload_location),
        ),
    ]
