# Generated by Django 2.0.6 on 2018-06-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('books', models.ManyToManyField(blank=True, to='books.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ManyToManyField(related_name='_book_subject_+', to='books.Genre'),
        ),
    ]
