# Generated by Django 2.0.6 on 2018-07-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('genre', models.ManyToManyField(blank=True, to='books.Genre')),
            ],
        ),
    ]
