# Generated by Django 2.0.6 on 2018-06-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180616_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subjects',
            field=models.ManyToManyField(to='books.Genre'),
        ),
    ]
