# Generated by Django 2.0.6 on 2018-07-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_member_reserved'),
        ('books', '0002_book_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='book',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
