# Generated by Django 2.0.6 on 2018-06-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180612_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
