# Generated by Django 2.0.6 on 2018-07-25 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180724_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotioncodes',
            name='genres',
        ),
        migrations.AddField(
            model_name='promotioncodes',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Genre'),
        ),
    ]
