# Generated by Django 2.0.6 on 2018-06-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20180612_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='subject',
        ),
        migrations.AddField(
            model_name='book',
            name='subjects',
            field=models.ManyToManyField(related_name='_book_subjects_+', to='books.Genre'),
        ),
    ]
