# Generated by Django 2.0.6 on 2018-06-13 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20180612_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='subject',
            new_name='subjects',
        ),
    ]
