# Generated by Django 2.0.4 on 2018-06-11 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=60)),
                ('books_owned', models.ManyToManyField(blank=True, to='books.Book')),
                ('member_actual', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='members.Member')),
            ],
        ),
    ]
