# Generated by Django 2.0.6 on 2018-07-21 00:37

from django.db import migrations, models
import django.db.models.deletion
import vendors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=60, unique=True)),
                ('vendor_passcode', models.CharField(blank=True, default=vendors.models.generate_code, max_length=16)),
                ('physical_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Address')),
            ],
        ),
    ]
