# Generated by Django 2.0.6 on 2018-07-20 21:22

from django.db import migrations, models
import vendors.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_passcode',
            field=models.CharField(blank=True, default=vendors.models.generate_code, max_length=16),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
