# Generated by Django 2.0.6 on 2018-06-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_vendor_actual'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='member_actual',
        ),
        migrations.AddField(
            model_name='vendor',
            name='member_actual',
            field=models.ManyToManyField(related_name='_vendor_member_actual_+', to='members.Member'),
        ),
    ]
