# Generated by Django 2.0.6 on 2018-07-20 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20180719_0101'),
        ('vendors', '0002_auto_20180720_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='physical_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Address'),
        ),
    ]
