# Generated by Django 2.0.4 on 2018-06-11 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('books', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_used',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='members.Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cart.Cart'),
        ),
        migrations.AddField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
        migrations.AddField(
            model_name='cart',
            name='member_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='members.Member'),
        ),
    ]
