# Generated by Django 2.0.6 on 2018-07-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20180714_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
