# Generated by Django 2.0.6 on 2018-07-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_is_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=8),
            preserve_default=False,
        ),
    ]
