# Generated by Django 2.0.4 on 2018-06-11 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
        ('books', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=members.models.upload_location)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('birth_date', models.DateField()),
                ('recv_newsletter', models.BooleanField(default=True)),
                ('account_active', models.BooleanField(default=True)),
                ('authenticated', models.BooleanField(default=True)),
                ('authentication_key', models.CharField(blank=True, max_length=8)),
                ('admin', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_auth', models.BooleanField(default=False)),
                ('client_auth', models.BooleanField(default=False)),
                ('cart', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='+', to='cart.Cart')),
                ('client_actual',
                 models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                      to='client.Client')),
                ('order', models.ManyToManyField(blank=True, related_name='_member_order_+', to='cart.Order')),
                ('purchased', models.ManyToManyField(blank=True, related_name='_member_purchased_+', to='books.Book')),
                ('reserved', models.ManyToManyField(blank=True, to='books.Reservation')),
                ('saved_addresses',
                 models.ManyToManyField(blank=True, related_name='_member_saved_addresses_+', to='members.Address')),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
