# Generated by Django 2.0.6 on 2018-07-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='receive_newsletter',
            field=models.BooleanField(default=True),
        ),
    ]
