# Generated by Django 2.0.6 on 2018-07-16 00:53

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(blank=True, default='members/images/default_member.jpg', null=True, upload_to=members.models.upload_location),
        ),
    ]
