# Generated by Django 2.0.6 on 2018-07-19 05:01

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180715_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(default='members/images/default_member.jpg', upload_to=members.models.upload_location),
        ),
    ]
