# Generated by Django 2.0.6 on 2018-07-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
