# Generated by Django 2.0.6 on 2018-06-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180616_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='vendor',
            field=models.ManyToManyField(blank=True, to='vendors.Vendor'),
        ),
    ]
