# Generated by Django 2.0.6 on 2018-06-16 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('members', '0003_auto_20180616_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='vendor',
        ),
        migrations.AddField(
            model_name='member',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor'),
        ),
    ]
