# Generated by Django 2.0.6 on 2018-06-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20180612_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='public_account',
            field=models.BooleanField(default=True),
        ),
    ]
