# Generated by Django 2.0.6 on 2018-07-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_hex_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
