# Generated by Django 2.0.6 on 2018-07-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_is_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='reserved',
        ),
    ]
