# Generated by Django 2.0.6 on 2018-06-16 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20180616_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='member',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='cart.Cart'),
        ),
        migrations.AlterField(
            model_name='member',
            name='order',
            field=models.ManyToManyField(blank=True, related_name='order', to='cart.Order'),
        ),
        migrations.AlterField(
            model_name='member',
            name='purchased',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
        migrations.AlterField(
            model_name='member',
            name='saved_addresses',
            field=models.ManyToManyField(blank=True, related_name='address', to='members.Address'),
        ),
    ]
